Use correct function names in documentation
apoelstra/secp256k1-zkp pull request #9
Opened 2019-03-15 17:05 UTC by guggero

While reading the documentation I noticed some function names have changed since this text was written. I hope I picked the right ones.

Some line breaks had to be changed too as to respect the maximum line length.

2019-03-18 14:56 UTC, apoelstra commented
Thank you!

I think with this file we probably need to mostly rewrite it; I added it to the repo to help with review/further development because it was the most complete description of the algebra that we had laying around. This PR is still very WIP.

cc @jonasnick

2019-03-18 16:27 UTC, guggero commented
I'm aware this PR is still WIP. But I was reading through the description and the code and noticed some things (see #10).
I thought it might be helpful for others who have an early look at your work and want to understand it or get it running.

2019-03-18 22:05 UTC, jonasnick requested changes
Thanks for your help! I left a few minor comments.

2019-03-18 22:05 UTC, jonasnick commented on src/modules/thresholdsig/threshold.md
> +3. Each signer modifies her secret key by multiplying it with the coefficient
I don't think this multiplication happens. I also left a comment about that in the original PR.

2019-03-18 22:05 UTC, jonasnick commented on src/modules/thresholdsig/threshold.md
> +   This is done with `secp256k1_musig_session_get_public_nonce`. Sends the
nonce and commitment are created with `secp256k1_musig_session_initialize` and the nonce can be obtained with `secp256k1_musig_session_get_public_nonce`.

2019-03-18 22:05 UTC, jonasnick commented on src/modules/thresholdsig/threshold.md
> +musig_generate_nonce C    ->
There's no `musig_generate_nonce`. This is now done in `session_initialize`. How about swapping `musig_generate_nonce` with `session_initialize` and replacing `musig_generate_nonce` with `musig_get_public_nonce`?

2019-03-24 12:08 UTC, guggero commented
@jonasnick Thank you for your input!
I've updated my changes accordingly.

2019-03-25 10:12 UTC, jonasnick commented
ACK 0a734caea84fc6c2f16d9c37562b84198312d09c

2019-04-01 15:27 UTC, jonasnick commented
This is ready to merge imho

2019-04-10 21:46 UTC, apoelstra commented
Sure

2019-04-10 21:46 UTC, merged